# Generated by Django 4.2.16 on 2024-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_planned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
